# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/wat_widget.ui'
#
# Created: Sun Jul  8 23:09:12 2018
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(381, 231)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.taurusLed = TaurusLed(Form)
        self.taurusLed.setObjectName(_fromUtf8("taurusLed"))
        self.gridLayout.addWidget(self.taurusLed, 1, 1, 1, 1)
        self.taurusLed_5 = TaurusLed(Form)
        self.taurusLed_5.setObjectName(_fromUtf8("taurusLed_5"))
        self.gridLayout.addWidget(self.taurusLed_5, 1, 5, 1, 1)
        self.taurusLed_3 = TaurusLed(Form)
        self.taurusLed_3.setObjectName(_fromUtf8("taurusLed_3"))
        self.gridLayout.addWidget(self.taurusLed_3, 1, 3, 1, 1)
        self.taurusLed_18 = TaurusLed(Form)
        self.taurusLed_18.setObjectName(_fromUtf8("taurusLed_18"))
        self.gridLayout.addWidget(self.taurusLed_18, 2, 8, 1, 1)
        self.taurusLed_13 = TaurusLed(Form)
        self.taurusLed_13.setObjectName(_fromUtf8("taurusLed_13"))
        self.gridLayout.addWidget(self.taurusLed_13, 2, 3, 1, 1)
        self.taurusLed_4 = TaurusLed(Form)
        self.taurusLed_4.setObjectName(_fromUtf8("taurusLed_4"))
        self.gridLayout.addWidget(self.taurusLed_4, 1, 4, 1, 1)
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setFrameShape(QtGui.QFrame.Box)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.taurusLed_2 = TaurusLed(Form)
        self.taurusLed_2.setObjectName(_fromUtf8("taurusLed_2"))
        self.gridLayout.addWidget(self.taurusLed_2, 1, 2, 1, 1)
        self.taurusLed_14 = TaurusLed(Form)
        self.taurusLed_14.setObjectName(_fromUtf8("taurusLed_14"))
        self.gridLayout.addWidget(self.taurusLed_14, 2, 4, 1, 1)
        self.taurusLed_6 = TaurusLed(Form)
        self.taurusLed_6.setObjectName(_fromUtf8("taurusLed_6"))
        self.gridLayout.addWidget(self.taurusLed_6, 1, 6, 1, 1)
        self.taurusLed_29 = TaurusLed(Form)
        self.taurusLed_29.setObjectName(_fromUtf8("taurusLed_29"))
        self.gridLayout.addWidget(self.taurusLed_29, 4, 2, 1, 1)
        self.taurusLed_32 = TaurusLed(Form)
        self.taurusLed_32.setObjectName(_fromUtf8("taurusLed_32"))
        self.gridLayout.addWidget(self.taurusLed_32, 4, 5, 1, 1)
        self.taurusLed_33 = TaurusLed(Form)
        self.taurusLed_33.setObjectName(_fromUtf8("taurusLed_33"))
        self.gridLayout.addWidget(self.taurusLed_33, 4, 6, 1, 1)
        self.taurusLed_34 = TaurusLed(Form)
        self.taurusLed_34.setObjectName(_fromUtf8("taurusLed_34"))
        self.gridLayout.addWidget(self.taurusLed_34, 4, 7, 1, 1)
        self.label = QtGui.QLabel(Form)
        self.label.setFrameShape(QtGui.QFrame.Panel)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.taurusLed_7 = TaurusLed(Form)
        self.taurusLed_7.setObjectName(_fromUtf8("taurusLed_7"))
        self.gridLayout.addWidget(self.taurusLed_7, 1, 7, 1, 1)
        self.taurusLed_24 = TaurusLed(Form)
        self.taurusLed_24.setObjectName(_fromUtf8("taurusLed_24"))
        self.gridLayout.addWidget(self.taurusLed_24, 3, 4, 1, 1)
        self.taurusLed_15 = TaurusLed(Form)
        self.taurusLed_15.setObjectName(_fromUtf8("taurusLed_15"))
        self.gridLayout.addWidget(self.taurusLed_15, 2, 5, 1, 1)
        self.taurusLed_8 = TaurusLed(Form)
        self.taurusLed_8.setObjectName(_fromUtf8("taurusLed_8"))
        self.gridLayout.addWidget(self.taurusLed_8, 1, 8, 1, 1)
        self.taurusLed_23 = TaurusLed(Form)
        self.taurusLed_23.setObjectName(_fromUtf8("taurusLed_23"))
        self.gridLayout.addWidget(self.taurusLed_23, 3, 3, 1, 1)
        self.taurusLed_31 = TaurusLed(Form)
        self.taurusLed_31.setObjectName(_fromUtf8("taurusLed_31"))
        self.gridLayout.addWidget(self.taurusLed_31, 4, 4, 1, 1)
        self.taurusLed_30 = TaurusLed(Form)
        self.taurusLed_30.setObjectName(_fromUtf8("taurusLed_30"))
        self.gridLayout.addWidget(self.taurusLed_30, 4, 3, 1, 1)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.taurusLed_25 = TaurusLed(Form)
        self.taurusLed_25.setObjectName(_fromUtf8("taurusLed_25"))
        self.gridLayout.addWidget(self.taurusLed_25, 3, 5, 1, 1)
        self.taurusLed_35 = TaurusLed(Form)
        self.taurusLed_35.setObjectName(_fromUtf8("taurusLed_35"))
        self.gridLayout.addWidget(self.taurusLed_35, 4, 8, 1, 1)
        self.taurusLed_36 = TaurusLed(Form)
        self.taurusLed_36.setObjectName(_fromUtf8("taurusLed_36"))
        self.gridLayout.addWidget(self.taurusLed_36, 4, 9, 1, 1)
        self.taurusLed_37 = TaurusLed(Form)
        self.taurusLed_37.setObjectName(_fromUtf8("taurusLed_37"))
        self.gridLayout.addWidget(self.taurusLed_37, 4, 10, 1, 1)
        self.taurusLed_17 = TaurusLed(Form)
        self.taurusLed_17.setObjectName(_fromUtf8("taurusLed_17"))
        self.gridLayout.addWidget(self.taurusLed_17, 2, 7, 1, 1)
        self.taurusLed_10 = TaurusLed(Form)
        self.taurusLed_10.setObjectName(_fromUtf8("taurusLed_10"))
        self.gridLayout.addWidget(self.taurusLed_10, 1, 10, 1, 1)
        self.taurusLed_28 = TaurusLed(Form)
        self.taurusLed_28.setObjectName(_fromUtf8("taurusLed_28"))
        self.gridLayout.addWidget(self.taurusLed_28, 4, 1, 1, 1)
        self.taurusLed_27 = TaurusLed(Form)
        self.taurusLed_27.setObjectName(_fromUtf8("taurusLed_27"))
        self.gridLayout.addWidget(self.taurusLed_27, 3, 7, 1, 1)
        self.taurusLed_21 = TaurusLed(Form)
        self.taurusLed_21.setObjectName(_fromUtf8("taurusLed_21"))
        self.gridLayout.addWidget(self.taurusLed_21, 3, 1, 1, 1)
        self.taurusLed_19 = TaurusLed(Form)
        self.taurusLed_19.setObjectName(_fromUtf8("taurusLed_19"))
        self.gridLayout.addWidget(self.taurusLed_19, 2, 9, 1, 1)
        self.taurusLed_11 = TaurusLed(Form)
        self.taurusLed_11.setObjectName(_fromUtf8("taurusLed_11"))
        self.gridLayout.addWidget(self.taurusLed_11, 2, 1, 1, 1)
        self.taurusLed_9 = TaurusLed(Form)
        self.taurusLed_9.setObjectName(_fromUtf8("taurusLed_9"))
        self.gridLayout.addWidget(self.taurusLed_9, 1, 9, 1, 1)
        self.taurusLed_22 = TaurusLed(Form)
        self.taurusLed_22.setObjectName(_fromUtf8("taurusLed_22"))
        self.gridLayout.addWidget(self.taurusLed_22, 3, 2, 1, 1)
        self.taurusLed_20 = TaurusLed(Form)
        self.taurusLed_20.setObjectName(_fromUtf8("taurusLed_20"))
        self.gridLayout.addWidget(self.taurusLed_20, 2, 10, 1, 1)
        self.taurusLed_26 = TaurusLed(Form)
        self.taurusLed_26.setObjectName(_fromUtf8("taurusLed_26"))
        self.gridLayout.addWidget(self.taurusLed_26, 3, 6, 1, 1)
        self.taurusLed_16 = TaurusLed(Form)
        self.taurusLed_16.setObjectName(_fromUtf8("taurusLed_16"))
        self.gridLayout.addWidget(self.taurusLed_16, 2, 6, 1, 1)
        self.taurusLed_12 = TaurusLed(Form)
        self.taurusLed_12.setObjectName(_fromUtf8("taurusLed_12"))
        self.gridLayout.addWidget(self.taurusLed_12, 2, 2, 1, 1)
        self.taurusLed_38 = TaurusLed(Form)
        self.taurusLed_38.setObjectName(_fromUtf8("taurusLed_38"))
        self.gridLayout.addWidget(self.taurusLed_38, 5, 1, 1, 1)
        self.taurusLed_39 = TaurusLed(Form)
        self.taurusLed_39.setObjectName(_fromUtf8("taurusLed_39"))
        self.gridLayout.addWidget(self.taurusLed_39, 5, 2, 1, 1)
        self.taurusLed_40 = TaurusLed(Form)
        self.taurusLed_40.setObjectName(_fromUtf8("taurusLed_40"))
        self.gridLayout.addWidget(self.taurusLed_40, 5, 3, 1, 1)
        self.taurusLed_41 = TaurusLed(Form)
        self.taurusLed_41.setObjectName(_fromUtf8("taurusLed_41"))
        self.gridLayout.addWidget(self.taurusLed_41, 5, 4, 1, 1)
        self.taurusLed_42 = TaurusLed(Form)
        self.taurusLed_42.setObjectName(_fromUtf8("taurusLed_42"))
        self.gridLayout.addWidget(self.taurusLed_42, 5, 5, 1, 1)
        self.taurusLed_43 = TaurusLed(Form)
        self.taurusLed_43.setObjectName(_fromUtf8("taurusLed_43"))
        self.gridLayout.addWidget(self.taurusLed_43, 5, 6, 1, 1)
        self.taurusLed_44 = TaurusLed(Form)
        self.taurusLed_44.setObjectName(_fromUtf8("taurusLed_44"))
        self.gridLayout.addWidget(self.taurusLed_44, 5, 7, 1, 1)
        self.taurusLed_45 = TaurusLed(Form)
        self.taurusLed_45.setObjectName(_fromUtf8("taurusLed_45"))
        self.gridLayout.addWidget(self.taurusLed_45, 5, 8, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_2.addWidget(self.pushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label_3.setText(_translate("Form", "Ring", None))
        self.label.setText(_translate("Form", "WAT", None))
        self.label_2.setText(_translate("Form", "Linac", None))
        self.pushButton.setText(_translate("Form", "Close", None))

from taurus.qt.qtgui.display import TaurusLed
